name: home_management_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  fl_chart: ^0.11.0
  encrypt: ^4.0.0
  shared_preferences: ^0.5.10
  get_it: ^4.0.4
  injectable: ^1.0.4
  intl: ^0.16.1
  datetime_picker_formfield: ^1.0.0
  outline_material_icons: ^0.1.1
  flutter_speed_dial: ^1.2.5
  flip_card: ^0.4.4
  queries: ^0.1.14
  local_auth: ^0.6.3+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
